### PR TITLE
issue #191: log cabin cannot start if open segment is full of 0s

### PR DESCRIPTION
**Pull request by nhardt**

### CODE REVIEW

**Comment by ongardie** [comment]
(linking this PR to issue #191)

**Comment by ongardie** [comment]
Travis CI is failing because of `scons check`:

    ./Storage/SegmentedLog.cc:997:  Lines should be <= 80 characters long  [whitespace/line_length] [2]

**Comment by nhardt** [comment]
ah, scons check. i couldn't remember/find the command to run the linter without doing the PR (i admit I didn't look that hard). will re-push

**Comment by nhardt** [comment]
as an aside, i've been using clang-format, you can drop a .clang-format file at the root of your tree and it will format everything for you adequately.

**Comment by nhardt** [comment]
unit tests pre/post:

[hardtnf@nate-maipo (11:35 AM) ((detached): test] $ ./test
[==========] Running 601 tests from 67 test cases.
2016-08-25 18:35:34.248180 Storage/SegmentedLog.cc:998 in loadOpenSegment() ERROR[4446:thread 1]: Segment version read from open-90 was 0, but this code can only read version 1 Exiting...
Aborted
[hardtnf@nate-maipo (11:35 AM) ((detached): test] $ ./test
[==========] Running 601 tests from 67 test cases.
[==========] 601 tests from 67 test cases ran. (1204 ms total)
[  PASSED  ] 601 tests.

**Comment by ongardie** [comment]
Thanks @nhardt, merged.

**Pull request merged**
