### PR TITLE
Fix assumption that unsigned longs are 64-bit

### PR DESCRIPTION
**Pull request by coruus**

### CODE REVIEW

**Comment by coruus** [comment]
Ugh. That's stupid. Hold off on that. :)

**Comment by ongardie** [comment]
There's a lot of places in the code where uint64_t is assumed to equal size_t, but I guess compiling for a 32-bit platform would warn about those.

But what's the goal here? Is there a non-64-bit platform that people would want to run LogCabin on?

**Comment by pyrovski** [comment]
I have a few 32-bit platforms that make up my set of non-laptop machines, so I am also affected by this.

**Comment by ongardie** [comment]
@pyrovski You have some 32-bit machines, but does it make sense to run LogCabin on them? There's a cost to supporting them, and I believe they're quickly becoming extinct.

**Comment by pyrovski** [comment]
I'm happy to make the changes, but it would help if you could point out an overview of what needs to be done.

**Comment by ongardie** [comment]
Making the initial change is part of the cost, but there's other aspects too:
 - The code gets messier. Even changing `"I have %lu apples"` to `"I have " PRIx64 " apples"` is harder for humans to parse (how many times do you want to recompile and rerun to get the spacing right on that simple message?). And I'd guess we'd need a few ifdefs here and there, and to change to some more awkward types.
 - There'd be ongoing maintenance effort required to make sure new changes don't break the 32-bit mode. For example, we'd have to add new compiler configurations to test each release: running through them takes time, and satisfying all of them with the same code tree is already quite challenging (with gcc 4.4 to 5.1, clang 3.4 to 3.7, and libc++ vs libstdc++ in 64-bit today).

So that's the cost, even if you submitted a patch. What's the benefit? What's your use case?

**Comment by pyrovski** [comment]
I'm not asking for continued maintenance; I'm happy to run tests myself. The use case is that I have an application that needs distributed consensus, and I happen to have a number of 32-bit systems. The benefit is that logcabin gets more users.

**Comment by ongardie** [comment]
Hey @pyrovski, I was chatting with @alcriceedu, who told me about the `%ju` format specifier to print out a uintmax_t. That seems to do no harm on a 64-bit machine and isn't any harder to read.

If you're still interested, you might try to find `%lu` and replace all with `%ju` project-wide. I suspect you'll see some compiler errors after that, but they might be tractable. Feel free to post distinct errors in here if they're giving you trouble.

**Comment by pyrovski** [comment]
Awesome; I didn't know about that. I think a couple of types will also have
to change because size_t is 32 bits.

On Thu, Mar 3, 2016 at 9:54 PM, Diego Ongaro <notifications@github.com>
wrote:

> Hey @pyrovski <https://github.com/pyrovski>, I was chatting with
> @alcriceedu <https://github.com/alcriceedu>, who told me about the %ju
> format specifier to print out a uintmax_t. That seems to do no harm on a
> 64-bit machine and isn't any harder to read.
>
> If you're still interested, you might try to find %lu and replace all
> with %ju project-wide. I suspect you'll see some compiler errors after
> that, but they might be tractable. Feel free to post distinct errors in
> here if they're giving you trouble.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logcabin/logcabin/pull/143#issuecomment-192119200>.
>



-- 

Peter Bailey
Mountain View, CA
Phone: (651) 538-0340

**Comment by ongardie** [comment]
@pyrovski 
>  I think a couple of types will also have to change because size_t is 32 bits.

Yes, agreed. I hope that doesn't affect too many files, but it's hard to estimate without trying it.

**Comment by pyrovski** [comment]
I'll get to this soon; first, I have to get employer permission to work on
it.

**Pull request closed without merging**
